<?php

/**
* Implements hook_theme().
*/
function hello_world_theme() {
    return [
      'hello_world_block' => [
        'variables' => [
          'active_tab' => NULL,
          'body_text' => NULL,
          'tabs' => [],      
        ],
      ],
    ];
}

/** 
*
* Register sugeestions by implementing hook_theme_suggestions_HooK()
*
*
*function hello_world_theme_suggestions_block(array $variables) {
*  $suggestions = [];
*  $suggestions[] = 'hello_world_block';
*
*  return $suggestions;
*}
*/